[package]
name = "poe_teasers"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
scraper.workspace = true
reqwest.workspace = true
serde.workspace = true
http = { path = "../http" }

[dev-dependencies]
tokio.workspace = true