[package]
name = "fresh_news"
version.workspace = true
edition.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
playwright = "0.0.20"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
