[package]
name = "ea_live_updates"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
regex = "1.11.1"
http_client = { path = "../http_client" }

[dev-dependencies]
tokio.workspace = true
