[package]
name = "rusty_vinnie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
poise = {git = "https://github.com/serenity-rs/poise.git", branch = "current"}
rand = "0.8.5"
tokio = { workspace = true }
fresh_news = {path = "../fresh_news"}